# Generated by Django 6.1 on 2026-09-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="conversation",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="chat.conversation"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(choices=[("COURSE_ANNOUNCEMENT", "Course Announcement"), ("INSTRUCTOR_MESSAGE", "Instructor Learning Notice"), ("CHAT_MESSAGE", "Chat Message"), ("SYSTEM", "System Notification")], default="COURSE_ANNOUNCEMENT", max_length=30),
        ),
    ]
