# Generated by Django 6.1 on 2026-09-04 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_alter_course_slug'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_code', models.CharField(db_index=True, help_text='Unique verifiable public certificate code', max_length=64, unique=True)),
                ('learner_full_name', models.CharField(help_text='Learner full name snapshot at time of completion', max_length=255)),
                ('course_title', models.CharField(help_text='Course title snapshot at time of completion', max_length=255)),
                ('instructor_name', models.CharField(help_text='Course instructor name snapshot at time of completion', max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['certificate_code'], name='certificate_certifi_0d7e7f_idx'), models.Index(fields=['learner', 'course'], name='certificate_learner_990875_idx'), models.Index(fields=['issued_at'], name='certificate_issued__ee7878_idx')],
                'constraints': [models.UniqueConstraint(fields=('learner', 'course'), name='unique_learner_course_certificate')],
            },
        ),
    ]
