# Generated by Django 6.1 on 2026-09-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursebookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(help_text='Server-generated storage path/key', max_length=500, unique=True)),
                ('storage_provider', models.CharField(default='supabase', help_text='Storage provider (supabase, aws_s3, etc.)', max_length=50)),
                ('original_filename', models.CharField(help_text='Original filename from upload', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the video file', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Video width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Video height in pixels', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('playback_url', models.URLField(blank=True, help_text='Secure playback URL (can be signed/temporary)')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to video thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(blank=True, help_text='When upload completed', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_type',
            field=models.CharField(choices=[('NONE', 'No Video'), ('EXTERNAL', 'External Video'), ('HOSTED', 'Hosted Video')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (for EXTERNAL video type)'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['video_type'], name='courses_les_video_t_6d0e85_idx'),
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_video', to='courses.lesson'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='courses_vid_status_d30bef_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['lesson'], name='courses_vid_lesson__f97846_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['storage_provider'], name='courses_vid_storage_0feda4_idx'),
        ),
    ]
