# Generated by Django 6.1 on 2026-09-15 13:36

from django.db import migrations


def migrate_existing_video_urls(apps, schema_editor):
    """
    Data migration to ensure backward compatibility.

    For existing lessons that have video_url populated,
    set video_type to EXTERNAL to maintain existing functionality.
    """
    Lesson = apps.get_model('courses', 'Lesson')

    # Find all lessons with video_url that don't have video_type set
    lessons_with_video = Lesson.objects.exclude(
        video_url=''
    ).exclude(video_url__isnull=True).exclude(video_type='EXTERNAL')

    # Update them to use EXTERNAL video type
    count = lessons_with_video.update(video_type='EXTERNAL')
    print(f"Migrated {count} lessons to EXTERNAL video type for backward compatibility")


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_lesson_video_type_alter_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_video_urls, migrations.RunPython.noop),
    ]
